### ISSUE TITLE
UpdateOperation data Map does not include actionOnlyFields

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#1764] opened 2024-02-25 14:00 UTC
When using `transformWrite`, the `data` Map only includes fields defined on the schema. Obvious work around is to just use the `input` object.

**Comment by lolopinto** [comment] 2024-02-25 19:39
i think this one is by design/wontfix

https://github.com/lolopinto/ent/blob/0b14f75ca8f10bca63ef42cfc6ed99bf39566d7f/ts/src/schema/schema.ts#L320-L330

```
// input. same input that's passed to Triggers, Observers, Validators. includes action-only fields 
   input: Data; 
   // data that'll be saved in the db 
```

maybe we need better documentation for this?

**Comment by Swahvay** [comment] 2024-02-25 22:25
That's fine if it's by design. When would `data` ever be more than a subset of `input`? Does `data` include triggers or field formatters or something?

**Comment by lolopinto** [comment] 2024-02-25 22:55
it includes default value for fields, formatted fields etc

what would be written to the database

**Comment by Swahvay** [comment] 2024-02-26 01:58
Gotchya. Feel free to close/change this to an add documentation ticket/whatever you want. 👍

**Closed** 2024-03-02 06:49 UTC
