### ISSUE TITLE
Cannot name field "data"

### ISSUE THREAD

**Issue by Swahvay** [lolopinto/ent#781] opened 2022-03-07 17:58 UTC
Had this field for a complex JSON type defined with a TS type, but then it had compilation errors because the `data` variable is already used internally.

**Comment by lolopinto** [comment] 2022-03-07 18:59
yah, this is a dupe of https://github.com/lolopinto/ent/issues/665

need to fix...

**Closed** 2022-03-07 19:16 UTC
